baseURL = "https://kottkrig.github.io/johanl.se/"
languageCode = "sv-se"
title = "Johan Larsson"
theme = "johanl-theme"

[author]
    name = "Johan Larsson"
    email = "johan@johanl.se"

[params]
  heading = "Hej, jag heter Johan."
  tagline = "Jag bygger webbsidor, appar och allsköns andra digitala ting. Just nu gör jag det hos [ETC](https://etc.se)."

[[params.social]]
	name = "@kottkrig på twitter →"
	link = "https://twitter.com/kottkrig"

[markup.goldmark.renderer]
  unsafe= true