baseURL = "http://example.org/"
languageCode = "sv-se"
title = "johanl.se"
theme = "johanl-theme"

[author]
    name = "Johan Larsson"

[params]
  author = "Nikola Tesla"
  tagline = "En slags blogg."

[markup.goldmark.renderer]
  unsafe= true